[project]
name = "hydra"
version = "0.1.0"
description = "Hunt sql commands in pcap"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyshark>=0.6",
    "tabulate>=0.9.0",
    "tqdm>=4.67.1",
]
